# Generated by Django 2.1.15 on 2021-07-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=10, null=True)),
                ('checking_account', models.IntegerField()),
                ('address', models.CharField(max_length=155)),
                ('phone_number', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('inn', models.CharField(max_length=10, null=True)),
                ('checking_account', models.IntegerField()),
                ('address', models.CharField(max_length=155)),
                ('phone_number', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='avatars/')),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=5)),
                ('passport_data', models.CharField(max_length=9)),
                ('inn', models.CharField(max_length=10, null=True)),
                ('marital_status', models.CharField(max_length=10)),
                ('actual_address', models.CharField(default=None, max_length=50)),
                ('passport_address', models.CharField(max_length=50)),
                ('work_status', models.CharField(max_length=50)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('law_status', models.BooleanField()),
                ('mobile_phone', models.CharField(max_length=14)),
                ('home_phone', models.CharField(max_length=14)),
                ('work_phone', models.CharField(max_length=14)),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Mahalla')),
            ],
        ),
        migrations.AddField(
            model_name='mahalla',
            name='rais',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahalla_boss', to='app.User_info'),
        ),
        migrations.AddField(
            model_name='mahalla',
            name='secretary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahalla_kotiba', to='app.User_info'),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_info'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_info'),
        ),
    ]
