# Generated by Django 2.1.15 on 2021-07-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210725_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='home_phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='photo',
            field=models.ImageField(default='assets/images/user.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='work_phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
