# Generated by Django 2.1.15 on 2021-07-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210726_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahalla',
            name='rais',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahalla_boss', to='app.User_info'),
        ),
        migrations.AlterField(
            model_name='mahalla',
            name='secretary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahalla_kotiba', to='app.User_info'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='mahalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Mahalla'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='photo',
            field=models.ImageField(default='core/static/assets/images/user.png', upload_to='avatars/'),
        ),
    ]
